using RT.Util.Lingo;

namespace TankIconMaker
{
    [LingoStringClass]
    sealed partial class Translation
    {
        // The following control was not added because it has no name: Game _directory:

        // The following control was not added because it has no name: _Game version:

        // The following control was not added because it has no name: _Icon maker:

        // The following control was not added because it has no name: De_faults

        // The following control was not added because it has no name: _Load

        // The following control was not added because it has no name: Sav_e

        // The following control was not added because it has no name: Save _as...

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString ctZoomCheckbox = "_Zoom";

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString ctWarning = "There were some problems; click this icon to see the details.";

        // The following control was not added because it has no name: _Reload data

        // The following control was not added because it has no name: _Save...

        // The following control was not added because it has no name: About...

#if DEBUG
        [LingoAutoGenerated]
#endif
        public TrString TankIconMakerWindow = "Tank Icon Maker";
    }
}
