using RT.Util.Lingo;

namespace TankIconMaker
{
    [LingoStringClass]
    sealed partial class Translation
    {
        // The following control was not added because it has no name: Game _directory:

        // The following control was not added because it has no name: _Game version:

        // The following control was not added because it has no name: _Icon style:

        // The following control was not added because it has no name: _New

        // The following control was not added because it has no name: _Delete

        // The following control was not added because it has no name: _More

        // The following control was not added because it has no name: Layers:

        [LingoAutoGenerated]
        public TrString ctZoomCheckbox = "_Zoom";

        // The following control was not added because it has no name: Language

        [LingoAutoGenerated]
        public TrString ctWarning = "There were some problems; click this icon to see the details.";

        // The following control was not added because it has no name: _Reload data

        // The following control was not added because it has no name: _Save...

        // The following control was not added because it has no name: About...

        [LingoAutoGenerated]
        public TrString TankIconMakerWindow = "Tank Icon Maker";
    }
}
