using RT.Util.Lingo;

namespace TankIconMaker
{
    [LingoStringClass, LingoInGroup(TranslationGroup.MainWindow)]
    sealed partial class MainWindowTranslation
    {
        // The following control was not added because it has no name: Tank Icon Maker

        [LingoAutoGenerated]
        public TrString ctGameDirLabel = "Game _directory:";

        [LingoAutoGenerated]
        public TrString ctGameVersionLabel = "_Game version:";

        [LingoAutoGenerated]
        public TrString ctIconStyleLabel = "_Icon style:";

        [LingoAutoGenerated]
        public TrString ctStyleNewLabel = "_New";

        [LingoAutoGenerated]
        public TrString ctStyleImportLabel = "Im_port";

        [LingoAutoGenerated]
        public TrString ctStyleExportLabel = "E_xport";

        [LingoAutoGenerated]
        public TrString ctUpvote = "Upvote the author of this style";

        [LingoAutoGenerated]
        public TrString ctStyleMoreLabel = "_More";

        [LingoAutoGenerated]
        public TrString ctStyleChangeName = "Change _name";

        [LingoAutoGenerated]
        public TrString ctStyleChangeAuthor = "Change _author";

        [LingoAutoGenerated]
        public TrString ctStyleDuplicate = "_Duplicate";

        [LingoAutoGenerated]
        public TrString ctStyleDelete = "D_elete";

        [LingoAutoGenerated]
        public TrString ctLayersLabel = "Layers:";

        [LingoAutoGenerated]
        public TrString ctLayersAddLayer = "Add _layer...";

        [LingoAutoGenerated]
        public TrString ctLayersAddEffect = "Add _effect...";

        [LingoAutoGenerated]
        public TrString ctLayersModify = "_Modify";

        [LingoAutoGenerated]
        public TrString ctLayersDelete = "_Delete";

        [LingoAutoGenerated]
        public TrString ctLayersMoveUp = "Move _up";

        [LingoAutoGenerated]
        public TrString ctLayersMoveDown = "Move d_own";

        [LingoAutoGenerated]
        public TrString ctLayersToggleVisibility = "Toggle _visibility";

        [LingoAutoGenerated]
        public TrString ctZoomCheckbox = "_Zoom";

        [LingoAutoGenerated]
        public TrString ctDisplayModeAll = "All tanks";

        [LingoAutoGenerated]
        public TrString ctDisplayModeOneEach = "One of each combination";

        [LingoAutoGenerated]
        public TrString ctLanguageLabel = "Language";

        [LingoAutoGenerated]
        public TrString ctWarning = "There were some problems; click this icon to see the details.";

        [LingoAutoGenerated]
        public TrString ctReloadLabel = "_Reload data";

        [LingoAutoGenerated]
        public TrString ctSaveLabel = "_Save...";

        [LingoAutoGenerated]
        public TrString ctAboutLabel = "About...";
    }
}
